# Generated by Django 3.1.3 on 2020-12-02 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyAPI', '0002_auto_20201202_1614'),
    ]

    operations = [
        migrations.RenameField(
            model_name='approvals',
            old_name='Education_Graduate',
            new_name='Education',
        ),
    ]
